[versions]
# Required stuff, https://fabricmc.net/develop/
minecraft = "1.21.7"
yarnMappings = "1.21.7+build.1"
fabricLoader = "0.16.14"

# Plugins
loom = "1.10-SNAPSHOT" # https://github.com/FabricMC/fabric-loom/releases


[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarnMappings" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }

[bundles]


[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }